services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


  gallery:
    build: gallery
    image: gallery-image
    container_name: gallery-container
    ports:
      - "8081:8081"
    depends_on:
      - postgres_db
      - kafka



  email-sender:
    build: email-sender
    image: email-sender-image
    container_name: email-sender-container
    ports:
      - "8083:8083"
    depends_on:
      - kafka



  postgres_db:
      image: postgres:13.7-alpine
      volumes:
        - /var/lib/postgresql/data/
      container_name: db_postgres-gallery-container
      ports:
        - "6541:5432"
      environment:
        - POSTGRES_DB=sgallery
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=iamroot






